/* DEMO providers only — fictional names. */
const PROVIDERS = [
  { id: "p01", name: "Dr. Ana Rivera", cred: "MD", specialty: "Primary Care", locationId: "wpr-1381", days: ["mon","tue","wed","thu","fri"], hours: "8:30-5:00", notes: "Spanish" },
  { id: "p02", name: "PA Jordan Lee", cred: "PA-C", specialty: "Urgent Care", locationId: "wpr-1381", days: ["mon","tue","wed","thu","fri","sat"], hours: "8:30-5:00", notes: "Walk-in UC" },
  { id: "p03", name: "Dr. Priya Shah", cred: "DPM", specialty: "Podiatry", locationId: "mcgraw-1990", days: ["mon","wed","fri"], hours: "9:00-4:00", notes: "" },
  { id: "p04", name: "Dr. Camille Ortiz", cred: "MD", specialty: "Women's Health", locationId: "mcgraw-1990", days: ["tue","thu"], hours: "9:00-5:00", notes: "IUD / well-woman" },
  { id: "p05", name: "Dr. Camille Ortiz", cred: "MD", specialty: "Women's Health", locationId: "wbr-1434", days: ["mon","wed","fri"], hours: "9:00-5:00", notes: "Also at McGraw Tue/Thu" },
  { id: "p06", name: "Dr. Ethan Cole", cred: "MD", specialty: "Endocrinology", locationId: "wbr-1434", days: ["tue","thu"], hours: "9:00-3:00", notes: "" },
  { id: "p07", name: "Dr. Lina Park", cred: "MD", specialty: "ENT", locationId: "wbr-1434", days: ["wed"], hours: "10:00-4:00", notes: "Specialty day" },
  { id: "p08", name: "Dr. Marcus Bell", cred: "MD", specialty: "Gastroenterology", locationId: "tremont-3134", days: ["mon","tue","thu"], hours: "8:00-4:00", notes: "" },
  { id: "p09", name: "Dr. Sofia Alvarez", cred: "MD", specialty: "Pulmonology", locationId: "tremont-3134", days: ["wed","fri"], hours: "9:00-3:00", notes: "" },
  { id: "p10", name: "Dr. James Okonkwo", cred: "MD", specialty: "Cardiovascular", locationId: "arthur-2445", days: ["mon","tue","wed","thu"], hours: "8:30-4:30", notes: "" },
  { id: "p11", name: "Dr. James Okonkwo", cred: "MD", specialty: "Cardiovascular", locationId: "halperin-2601", days: ["fri"], hours: "8:30-1:00", notes: "Imaging / vascular day" },
  { id: "p12", name: "Dr. Helen Cho", cred: "MD", specialty: "Neurology", locationId: "arthur-2445", days: ["tue","thu"], hours: "9:00-3:00", notes: "" },
  { id: "p13", name: "Dr. Rafael Mendes", cred: "DPM", specialty: "Podiatry", locationId: "arthur-2445", days: ["mon","wed","fri"], hours: "9:00-4:00", notes: "" },
  { id: "p14", name: "NP Maya Thompson", cred: "FNP-C", specialty: "Primary Care", locationId: "wpr-2720", days: ["mon","tue","wed","thu","fri"], hours: "8:30-5:00", notes: "" },
  { id: "p15", name: "PA Chris Nguyen", cred: "PA-C", specialty: "Urgent Care", locationId: "wpr-2720", days: ["sat","sun"], hours: "8:30-12:00", notes: "Weekend UC" },
  { id: "p16", name: "Dr. Aisha Rahman", cred: "MD", specialty: "Cardiovascular", locationId: "eastch-2304", days: ["mon","wed","fri"], hours: "9:00-4:00", notes: "" },
  { id: "p17", name: "Dr. Priya Shah", cred: "DPM", specialty: "Podiatry", locationId: "eastch-2304", days: ["tue","thu"], hours: "9:00-3:00", notes: "Also McGraw M/W/F" },
  { id: "p18", name: "Dr. Luis Herrera", cred: "MD", specialty: "Primary Care", locationId: "e149-828", days: ["mon","tue","wed","thu","fri"], hours: "8:30-5:00", notes: "Spanish" },
  { id: "p19", name: "PA Jordan Lee", cred: "PA-C", specialty: "Urgent Care", locationId: "e138-542", days: ["sat"], hours: "8:30-12:00", notes: "Covers Mott Haven Sat" },
  { id: "p20", name: "Dr. Nora Bennett", cred: "MD", specialty: "Women's Health", locationId: "elton-899", days: ["mon","tue","wed","thu"], hours: "9:00-5:00", notes: "" },
  { id: "p21", name: "Dr. Nora Bennett", cred: "MD", specialty: "Women's Health", locationId: "gc-1532", days: ["fri"], hours: "9:00-1:00", notes: "" },
  { id: "p22", name: "Dr. Kevin Walsh", cred: "MD", specialty: "Primary Care", locationId: "univ-1550", days: ["mon","tue","wed","thu","fri"], hours: "8:30-5:00", notes: "" },
  { id: "p23", name: "Dr. Amara Diallo", cred: "MD", specialty: "Primary Care", locationId: "riv-5667", days: ["mon","tue","wed","thu","fri"], hours: "8:30-5:00", notes: "Riverdale" },
  { id: "p24", name: "PA Sam Patel", cred: "PA-C", specialty: "Urgent Care", locationId: "riv-5667", days: ["mon","tue","wed","thu","fri","sat"], hours: "8:30-5:00", notes: "" },
  { id: "p25", name: "Dr. Grace Kim", cred: "MD", specialty: "Primary Care", locationId: "wpr-3991", days: ["mon","wed","fri"], hours: "8:30-5:00", notes: "Wakefield" },
  { id: "p26", name: "Dr. Grace Kim", cred: "MD", specialty: "Primary Care", locationId: "bway-5235", days: ["tue","thu"], hours: "8:30-5:00", notes: "Kingsbridge days" },
  { id: "p27", name: "Dr. Omar Farouk", cred: "MD", specialty: "Vascular", locationId: "union-8989", days: ["tue","thu"], hours: "9:00-3:00", notes: "Queens site" },
  { id: "p28", name: "Dr. Rafael Mendes", cred: "DPM", specialty: "Podiatry", locationId: "union-8989", days: ["sat"], hours: "9:00-1:00", notes: "" },
  { id: "p29", name: "Dr. Elena Rossi", cred: "MD", specialty: "Pain Management", locationId: "union-8989", days: ["wed"], hours: "10:00-4:00", notes: "" },
  { id: "p30", name: "Dr. Thomas Greene", cred: "MD", specialty: "Cardiovascular", locationId: "halperin-2601", days: ["mon","tue","wed","thu"], hours: "8:00-4:00", notes: "CV + imaging center" },
  { id: "p31", name: "NP Bianca Cruz", cred: "FNP-C", specialty: "Primary Care", locationId: "gc-1532", days: ["mon","tue","wed","thu","fri"], hours: "8:30-5:00", notes: "Open MRI site" },
  { id: "p32", name: "PA Chris Nguyen", cred: "PA-C", specialty: "Urgent Care", locationId: "gc-1532", days: ["mon","tue","wed","thu","fri"], hours: "8:30-5:00", notes: "" },
  { id: "p33", name: "Dr. Helen Cho", cred: "MD", specialty: "Imaging", locationId: "gc-1532", days: ["mon","wed"], hours: "9:00-4:00", notes: "Reads / consults" },
  { id: "p34", name: "Dr. Luis Herrera", cred: "MD", specialty: "Primary Care", locationId: "stann-800", days: ["sat"], hours: "8:30-12:00", notes: "New St. Ann coverage" },
  { id: "p35", name: "NP Maya Thompson", cred: "FNP-C", specialty: "Primary Care", locationId: "gc-2015", days: ["sat"], hours: "8:30-12:00", notes: "" },
  { id: "p36", name: "Dr. Sofia Alvarez", cred: "MD", specialty: "Primary Care", locationId: "castle-616", days: ["mon","tue","thu"], hours: "8:30-5:00", notes: "" },
  { id: "p37", name: "Dr. Kevin Walsh", cred: "MD", specialty: "Primary Care", locationId: "plimpton-1539", days: ["sat"], hours: "8:30-12:00", notes: "" },
  { id: "p38", name: "Dr. Aisha Rahman", cred: "MD", specialty: "Primary Care", locationId: "e183-108", days: ["tue","thu"], hours: "9:00-4:00", notes: "Fordham" },
  { id: "p39", name: "PA Sam Patel", cred: "PA-C", specialty: "Urgent Care", locationId: "e149-432", days: ["sun"], hours: "8:30-12:00", notes: "Sunday Hub coverage" },
  { id: "p40", name: "Dr. Ana Rivera", cred: "MD", specialty: "Primary Care", locationId: "benedict-2034", days: ["sat"], hours: "8:30-12:00", notes: "" }
];
